### ISSUE TITLE
Dependency injection error

### ISSUE THREAD

**Issue by Anuuthpala** [simonfaltum/AspNetCore.Identity.Dapper#1]
Please find following error while registering services in startup. Thank you.

services.AddIdentityCore<ApplicationUser>(options =>
            {
                options.User.AllowedUserNameCharacters = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-._@+";
                options.User.RequireUniqueEmail = true;

                options.Password.RequireDigit = true;
                options.Password.RequiredLength = 8;
                options.Password.RequireLowercase = true;
                options.Password.RequireNonAlphanumeric = false;
                options.Password.RequireUppercase = true;
            })
            .AddRoles<ApplicationRole>()
            .AddDapperStores(options =>
            {
                options.ConnectionString = "my connectionstring";
                // options.DbSchema = "my schema";
            })
            .AddDefaultTokenProviders();
            services.AddControllers();

An error occurred while starting the application.
AggregateException: Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: Microsoft.AspNetCore.Identity.DataProtectorTokenProvider`1[AspNetCore.Identity.Dapper.Models.ApplicationUser] Lifetime: Transient ImplementationType: Microsoft.AspNetCore.Identity.DataProtectorTokenProvider`1[AspNetCore.Identity.Dapper.Models.ApplicationUser]': Unable to resolve service for type 'Microsoft.AspNetCore.DataProtection.IDataProtectionProvider' while attempting to activate 'Microsoft.AspNetCore.Identity.DataProtectorTokenProvider`1[AspNetCore.Identity.Dapper.Models.ApplicationUser]'.)
Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(IEnumerable<ServiceDescriptor> serviceDescriptors, IServiceProviderEngine engine, ServiceProviderOptions options)

InvalidOperationException: Error while validating the service descriptor 'ServiceType: Microsoft.AspNetCore.Identity.DataProtectorTokenProvider`1[AspNetCore.Identity.Dapper.Models.ApplicationUser] Lifetime: Transient ImplementationType: Microsoft.AspNetCore.Identity.DataProtectorTokenProvider`1[AspNetCore.Identity.Dapper.Models.ApplicationUser]': Unable to resolve service for type 'Microsoft.AspNetCore.DataProtection.IDataProtectionProvider' while attempting to activate 'Microsoft.AspNetCore.Identity.DataProtectorTokenProvider`1[AspNetCore.Identity.Dapper.Models.ApplicationUser]'.
Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.ValidateService(ServiceDescriptor descriptor)

AggregateException: Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: Microsoft.AspNetCore.Identity.DataProtectorTokenProvider`1[AspNetCore.Identity.Dapper.Models.ApplicationUser] Lifetime: Transient ImplementationType: Microsoft.AspNetCore.Identity.DataProtectorTokenProvider`1[AspNetCore.Identity.Dapper.Models.ApplicationUser]': Unable to resolve service for type 'Microsoft.AspNetCore.DataProtection.IDataProtectionProvider' while attempting to activate 'Microsoft.AspNetCore.Identity.DataProtectorTokenProvider`1[AspNetCore.Identity.Dapper.Models.ApplicationUser]'.)
Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(IEnumerable<ServiceDescriptor> serviceDescriptors, IServiceProviderEngine engine, ServiceProviderOptions options)
Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(IServiceCollection services, ServiceProviderOptions options)
Microsoft.Extensions.DependencyInjection.DefaultServiceProviderFactory.CreateServiceProvider(IServiceCollection containerBuilder)
Microsoft.Extensions.Hosting.Internal.ServiceFactoryAdapter<TContainerBuilder>.CreateServiceProvider(object containerBuilder)
Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
Microsoft.Extensions.Hosting.HostBuilder.Build()
WebApplication1.Program.Main(string[] args) in Program.cs
+
            CreateHostBuilder(args).Build().Run();

Show raw exception details
InvalidOperationException: Error while validating the service descriptor 'ServiceType: Microsoft.AspNetCore.Identity.DataProtectorTokenProvider`1[AspNetCore.Identity.Dapper.Models.ApplicationUser] Lifetime: Transient ImplementationType: Microsoft.AspNetCore.Identity.DataProtectorTokenProvider`1[AspNetCore.Identity.Dapper.Models.ApplicationUser]': Unable to resolve service for type 'Microsoft.AspNetCore.DataProtection.IDataProtectionProvider' while attempting to activate 'Microsoft.AspNetCore.Identity.DataProtectorTokenProvider`1[AspNetCore.Identity.Dapper.Models.ApplicationUser]'.
Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.ValidateService(ServiceDescriptor descriptor)
Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(IEnumerable<ServiceDescriptor> serviceDescriptors, IServiceProviderEngine engine, ServiceProviderOptions options)

Show raw exception details
.NET 5.0.1-servicing.20575.16 X64 v5.0.0.0    |   Microsoft.AspNetCore.Hosting version 5.0.1+fc93e595ceffbb1e3e85532bf454e92a6a80dd6b

**Comment by simonfaltum** [comment]
I am not entirely sure I am following what your problem is. 
It looks like you are calling services.AddIdentityCore without giving it an argument for the specified user type (TUser)?

Using ApplicationUser, you have to do it like below

 services.AddIdentityCore**<ApplicationUser>**(options =>
{
            //omitted
}

Please see microsoft documentation: https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.identityservicecollectionextensions.addidentitycore?view=aspnetcore-5.0

**Comment by Anuuthpala** [comment]
Hi Simonfaltum,

Thank you for quick reply.
I didn't do any modification to your code. It's the same code you posted under "Example with AddIdentityCore" in github.
I just added your NuGet package "VeryGood.AspNetCore.Identity.Dapper" and ran with below code.



services.AddIdentityCore\<ApplicationUser\>(options =>
            {
                options.User.AllowedUserNameCharacters = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-._@+';
                options.User.RequireUniqueEmail = true;
                options.Password.RequireDigit = true;
                options.Password.RequiredLength = 8;
                options.Password.RequireLowercase = true;
                options.Password.RequireNonAlphanumeric = false;
                options.Password.RequireUppercase = true;
            })
            .AddRoles<ApplicationRole>()
            .AddDapperStores(options =>
            {
                options.ConnectionString = "connection string";
                // options.DbSchema = "my schema";
            })
            .AddDefaultTokenProviders();`

**Comment by simonfaltum** [comment]
Thank you, I will remove ".AddDefaultTokenProviders()" from my example to avoid this misunderstanding in the future 👍 

If you want to use .AddDefaultTokenProviders() then you need to call services.AddDataProtection(); before services.AddIdentityCore<ApplicationUser>(options =>...

**Comment by Anuuthpala** [comment]
Hi Simonfaltum,

Thank you. That fixed it 👍

**Comment by chenzuo** [comment]
> 
> 
> Thank you, I will remove ".AddDefaultTokenProviders()" from my example to avoid this misunderstanding in the future 👍
> 
> If you want to use .AddDefaultTokenProviders() then you need to call services.AddDataProtection(); before services.AddIdentityCore(options =>...

solved the problem that confused me, thanks !
